import { Router } from 'express';

import automatischRouter from '@/routes/internal/api/v1/automatisch.js';
import accessTokensRouter from '@/routes/internal/api/v1/access-tokens.js';
import usersRouter from '@/routes/internal/api/v1/users.js';
import flowsRouter from '@/routes/internal/api/v1/flows.js';
import stepsRouter from '@/routes/internal/api/v1/steps.js';
import appsRouter from '@/routes/internal/api/v1/apps.js';
import connectionsRouter from '@/routes/internal/api/v1/connections.js';
import executionsRouter from '@/routes/internal/api/v1/executions.js';
import adminUsersRouter from '@/routes/internal/api/v1/admin/users.js';
import adminRolesRouter from '@/routes/internal/api/v1/admin/roles.js';
import adminPermissionsRouter from '@/routes/internal/api/v1/admin/permissions.js';
import adminTemplatesRouter from '@/routes/internal/api/v1/admin/templates.js';
import adminApiTokensRouter from '@/routes/internal/api/v1/admin/api-tokens.js';
import adminConfigRouter from '@/routes/internal/api/v1/admin/config.js';
import adminAppsRouter from '@/routes/internal/api/v1/admin/apps.js';
import adminSamlAuthProvidersRouter from '@/routes/internal/api/v1/admin/saml-auth-providers.js';
import installationUsersRouter from '@/routes/internal/api/v1/installation/users.js';
import foldersRouter from '@/routes/internal/api/v1/folders.js';
import templatesRouter from '@/routes/internal/api/v1/templates.js';
import formsRouter from '@/routes/internal/api/v1/forms.js';
import mcpServersRouter from '@/routes/internal/api/v1/mcp-servers.js';
import agentsRouter from '@/routes/internal/api/v1/agents.js';
import samlAuthProvidersRouter from '@/routes/internal/api/v1/saml-auth-providers.js';
import paymentRouter from '@/routes/internal/api/v1/payment.js';

const router = Router();

router.use('/v1/automatisch', automatischRouter);
router.use('/v1/access-tokens', accessTokensRouter);
router.use('/v1/users', usersRouter);
router.use('/v1/apps', appsRouter);
router.use('/v1/connections', connectionsRouter);
router.use('/v1/flows', flowsRouter);
router.use('/v1/steps', stepsRouter);
router.use('/v1/executions', executionsRouter);
router.use('/v1/admin/users', adminUsersRouter);
router.use('/v1/admin/roles', adminRolesRouter);
router.use('/v1/admin/permissions', adminPermissionsRouter);
router.use('/v1/admin/templates', adminTemplatesRouter);
router.use('/v1/admin/api-tokens', adminApiTokensRouter);
router.use('/v1/admin/config', adminConfigRouter);
router.use('/v1/admin/apps', adminAppsRouter);
router.use('/v1/admin/saml-auth-providers', adminSamlAuthProvidersRouter);
router.use('/v1/installation/users', installationUsersRouter);
router.use('/v1/folders', foldersRouter);
router.use('/v1/templates', templatesRouter);
router.use('/v1/forms', formsRouter);
router.use('/v1/mcp-servers', mcpServersRouter);
router.use('/v1/agents', agentsRouter);
router.use('/v1/saml-auth-providers', samlAuthProvidersRouter);
router.use('/v1/payment', paymentRouter);

export default router;
